# Generated by Django 3.2.15 on 2022-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название товара')),
                ('description', models.CharField(max_length=200, verbose_name='описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='стоимость товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
