# Generated by Django 3.2.15 on 2022-09-19 08:18

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название товара')),
                ('description', models.CharField(max_length=200, verbose_name='описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='стоимость товара')),
                ('currency', models.CharField(choices=[('rub', 'Russian Ruble'), ('usd', 'US Dollar')], default='rub', max_length=3, verbose_name='валюта товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='общая сумма заказа')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='стоимость товара')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество товара')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.order')),
            ],
            options={
                'verbose_name': 'товар в заказе',
                'verbose_name_plural': 'товары в заказе',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='orders', through='app_orders.OrderItems', to='app_orders.Item'),
        ),
    ]
