# Generated by Django 3.2.15 on 2022-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'Russian Ruble'), ('usd', 'US Dollar')], default='rub', max_length=3, verbose_name='валюта товара'),
        ),
    ]
