# Generated by Django 3.2.15 on 2022-09-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='общая сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='общая стоимость товара'),
        ),
    ]
