# Generated by Django 3.2.15 on 2022-09-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_auto_20220919_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('create', 'Заказ создан'), ('completed', 'Заказ оплачен')], default='create', max_length=20, verbose_name='статус заказа'),
        ),
    ]
