# Generated by Django 3.2.15 on 2022-09-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('create', 'Заказ создан'), ('completed', 'Заказ оплачен'), ('failed', 'Оплата отменена')], default='create', max_length=20, verbose_name='статус заказа'),
        ),
    ]
