version: '3.5'

services:
#  web:
#    container_name: payment_forms_web
#    build: .
#    command: sh -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
#    volumes:
#      - ./src/:/usr/src/app/
#    ports:
#      - "8000:8000"
#    env_file:
#      - ./.env
#    environment:
#      - DB_HOST=db
#    depends_on:
#      - db

  db:
    container_name: payment_forms_db
    image: postgres:13
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  db: