version: '3.5'

services:
  web:
    container_name: payment_forms_web
    image: payment-forms-web-prod:amd64
    command: gunicorn payment_forms.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/usr/src/static
      - media_data:/usr/src/media
    expose:
      - 8000
    restart: always
    env_file: .env.prod
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    container_name: payment_forms_db
    image: postgres:13
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/pgdata
    env_file: .env.prod
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile.prod
    volumes:
        - static_data:/usr/src/static
        - media_data:/usr/src/media
        - /etc/letsencrypt:/etc/letsencrypt
        - /certbot/www:/var/www/certbot
        - /certbot/log/letsencrypt:/var/log/letsencrypt
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
    depends_on:
      - web

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /certbot/www:/var/www/certbot
      - /certbot/log/letsencrypt:/var/log/letsencrypt
    command: certonly --reinstall --webroot --webroot-path /var/www/certbot --email $CERTBOT_EMAIL --agree-tos --no-eff-email -d $SITE_DOMAIN
    depends_on:
      - proxy

volumes:
  static_data:
  media_data:
  db: