version: '3.5'

services:
  db:
    container_name: payment_forms_db
    image: postgres:13-alpine
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  db: